server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: vendaModule
          uri: lb://venda-microservice
          predicates:
            - Path=/venda/**

        - id: loginModule
          uri: lb://login-microservice
          predicates:
            - Path=/login/**

        - id: estoqueModule
          uri: lb://estoque-microservice
          predicates:
            - Path=/estoque/**

