spring:
  application:
    name: login-microservice
server:
  port: 8100
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
springdoc:
  api-docs:
    path: passageiro-service/v3/api-docs