spring:
  application:
    name: venda-microservice
server:
  port: 8040
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
springdoc:
  api-docs:
    path: venda-service/v3/api-docs